return {
    -- Default
    fg = "#bdbdbd",
    bg = "#000000",
    window_bg = "#101010",
    window_accent = "#202020",

    -- Code
    attribute = "#bdbdbd",
    comment = "#bdbdbd",
    constant = "#bdbdbd",
    delimiter = "#bdbdbd",
    enum = "#bdbdbd",
    escape = "#bdbdbd",
    interface = "#bdbdbd",
    keyword = "#bdbdbd",
    macro = "#bdbdbd",
    member = "#bdbdbd",
    method = "#bdbdbd",
    module = "#bdbdbd",
    namespace = "#bdbdbd",
    number = "#bdbdbd",
    operator = "#bdbdbd",
    redundant = "#bdbdbd",
    string = "#bdbdbd",
    struct = "#bdbdbd",
    variable = "#bdbdbd",

    -- attribute = "#eb6c6c",
    -- comment = "#6ceb9f",
    -- constant = "#6cc0eb",
    -- delimiter = "#ae8f76",
    -- enum = "#6cebd2",
    -- escape = "#daeb6c",
    -- interface = "#8c6ceb",
    -- keyword = "#6cd3eb",
    -- macro = "#eb6c6c",
    -- member = "#eb6c98",
    -- method = "#6c9deb",
    -- module = "#ebb46b",
    -- namespace = "#eb8d69",
    -- number = "#daeb6c",
    -- operator = "#bdbdbd",
    -- redundant = "#787878",
    -- string = "#ae6ceb",
    -- struct = "#6c7deb",
    -- variable = "#bdbdbd",

    -- Other
    ok = "#6ceb9f",
    info = "#6c9deb",
    hint = "#6cebd2",
    warn = "#daeb6c",
    error = "#e22d2d",
    inlay = "#4f5258",
}
